version: 2.1

orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.1
commands:
  deploy-by-tag:
    description: Simulate a deploy command
    parameters:
      tag:
        description: Image tag
        type: string
    steps:
      - run: echo "Deploying << parameters.tag >>"
  restore-cache:
    description: Restores cache
    steps:
      - restore_cache:
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-
  save-cache:
    description: Restores cache
    steps:
      - save_cache:
          paths:
            - image.tar.gz
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
jobs:
  build-and-test:
    executor:
      name: docker/docker
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - restore-cache
      - run:
          name: Load docker image if exists
          command: |
            [ -f image.tar.gz ] && docker load -i image.tar.gz || echo "No cached image found"
      - run:
          name: Build Deps
          command: |
            docker build -t josephyi/orcinus-orca:deps --target deps .
      - run:
          name: Save cacheable
          command: |
            docker save josephyi/orcinus-orca:deps | gzip > image.tar.gz
      - save-cache
      # - node/with-cache:
      #     steps:
      #       - run: npm install
      #       - run: npm test
  build-docker-image:
    executor:
      name: docker/docker
    environment:
      DOCKER_BUILDKIT: "1"
      IMAGE_NAME: "josephyi/orcinus-orca"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - attach_workspace:
          at: /tmp/workspace
      - docker/build:
          image: $IMAGE_NAME
          extra_build_args: --progress=plain
      - run:
          name: Archive Docker image
          command: docker save $IMAGE_NAME | gzip > image.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar.gz
  publish-image:
    executor: docker/docker
    environment:
      IMAGE_NAME: "josephyi/orcinus-orca"
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.8
      - docker/check
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar.gz
      - docker/push:
          image: $IMAGE_NAME
  deploy-by-tag:
    executor: docker/docker
    steps:
      - checkout
      - deploy-by-tag:
          tag: $CIRCLE_SHA1
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - build-docker-image
      - publish-image:
          requires:
            - build-and-test
            - build-docker-image
  deploy:
    jobs:
      - approve:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-by-tag:
          requires:
            - approve
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
