version: 2.1

orbs:
  docker: circleci/docker@1.0.1
commands:
  deploy-by-tag:
    description: Simulate a deploy command
    parameters:
      tag:
        description: Image tag
        type: string
    steps:
      - run: echo "Deploying << parameters.tag >>"
jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.3.0
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-
      - run: yarn install --frozen-lockfile --cache-folder .cache
      - run: yarn test
      - save_cache:
          paths:
            - .cache
            - node_modules
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
  build-docker-image:
    executor:
      name: docker/docker
    working_directory: /mnt/ramdisk
    environment:
      DOCKER_BUILDKIT: "1"
      IMAGE_NAME: "josephyi/orcinus-orca"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - attach_workspace:
          at: /mnt/ramdisk/workspace
      - docker/build:
          image: $IMAGE_NAME
          extra_build_args: --progress=plain
      - run:
          name: Archive Docker image
          command: docker save $IMAGE_NAME | gzip > image.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar.gz
  publish-image:
    executor: docker/docker
    environment:
      IMAGE_NAME: "josephyi/orcinus-orca"
    steps:
      - attach_workspace:
          at: /mnt/ramdisk/workspace
      - setup_remote_docker:
          version: 19.03.8
      - docker/check
      - run:
          name: Load archived Docker image
          command: docker load -i /mnt/ramdisk/workspace/image.tar.gz
      - docker/push:
          image: $IMAGE_NAME
  deploy-by-tag:
    executor: docker/docker
    steps:
      - checkout
      - deploy-by-tag:
          tag: $CIRCLE_SHA1
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - build-docker-image
      - publish-image:
          requires:
            - build-and-test
            - build-docker-image
  deploy:
    jobs:
      - approve:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-by-tag:
          requires:
            - approve
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
